### ISSUE TITLE
Broken pipe for dcos-launch create -c launch.yaml

### ISSUE THREAD

**Issue by rimusz** [mesosphere/dcos-kubernetes-quickstart#48]
Running `make deploy` (after `make docker`) and getting broken pipe errors:
```
dcos-launch create -c launch.yaml
...
dcos-launch wait
[2017-12-18 16:13:58,791|dcos_launch.onprem|INFO]: Waiting for bare cluster provisioning status..
...
[2017-12-18 16:15:00,799|googleapiclient.discovery|INFO]: URL being requested: GET https://www.googleapis.com/deploymentmanager/v2/projects/xxx/global/deployments/dcos-cluster-mg8773wr?alt=json
Traceback (most recent call last):
  File "dcos_launch/cli.py", line 133, in <module>
  File "dcos_launch/cli.py", line 125, in main
  File "dcos_launch/cli.py", line 91, in do_main
  File "dcos_launch/onprem.py", line 99, in wait
  File "dcos_launch/gce.py", line 75, in wait
  File "site-packages/retrying.py", line 49, in wrapped_f
  File "site-packages/retrying.py", line 206, in call
  File "site-packages/retrying.py", line 247, in get
  File "site-packages/six.py", line 686, in reraise
  File "site-packages/retrying.py", line 200, in call
  File "dcos_launch/platforms/gce.py", line 271, in wait_for_completion
  File "dcos_launch/platforms/gce.py", line 135, in handle_exception
  File "dcos_launch/platforms/gce.py", line 251, in get_info
  File "site-packages/oauth2client/util.py", line 137, in positional_wrapper
  File "site-packages/googleapiclient/http.py", line 837, in execute
  File "site-packages/googleapiclient/http.py", line 176, in _retry_request
  File "site-packages/googleapiclient/http.py", line 163, in _retry_request
  File "site-packages/oauth2client/transport.py", line 169, in new_request
  File "site-packages/httplib2/__init__.py", line 1322, in request
  File "site-packages/httplib2/__init__.py", line 1072, in _request
  File "site-packages/httplib2/__init__.py", line 996, in _conn_request
  File "http/client.py", line 1106, in request
  File "http/client.py", line 1151, in _send_request
  File "http/client.py", line 1102, in endheaders
  File "http/client.py", line 934, in _send_output
  File "http/client.py", line 908, in send
  File "ssl.py", line 891, in sendall
  File "ssl.py", line 861, in send
  File "ssl.py", line 586, in write
BrokenPipeError: [Errno 32] Broken pipe
Failed to execute script cli
make: *** [launch-dcos] Error 255
```

Repeated `deploy` a few times, always getting the same errors.

**Comment by rimusz** [comment]
cannot reproduce anymore, closing
