### ISSUE TITLE
Exception when using custom TLS provisioning

### ISSUE THREAD

**Issue by pires** [mesosphere/dcos-kubernetes-quickstart#52]
As reported by @deric:

>I'm having the same issue with 0.4.0-1.9.0-beta. All artifacts seems to be downloaded in the work dir.
```
2018/01/11 10:58:59 Resolve disabled via -resolve=false: Skipping host resolution
2018/01/11 10:58:59 Template handling disabled via -template=false: Skipping any config templates
2018/01/11 10:58:59 No $MESOS_SANDBOX/.ssl directory found. Cannot install certificate. Error: stat /var/lib/mesos/slave/slaves/59336e89-bac9-44c0-ba44-78a66392b7b1-S8/frameworks/56308059-3e74-48f4-86a9-67f9bd519f44-0001/executors/dev_k8.69908f7c-f6be-11e7-8ff9-fe0d65b1eb4a/runs/82acd8eb-26f1-47c8-9dce-b72d3cfbb954/.ssl: no such file or directory
2018/01/11 10:58:59 Local IP --> 192.168.5.91
2018/01/11 10:58:59 SDK Bootstrap successful.
Exception in thread "main" com.mesosphere.sdk.kubernetes.scheduler.tls.exceptions.UnrecoverableTLSException: com.mesosphere.sdk.state.StateStoreException: Key cannot contain '/' (reason: LOGIC_ERROR)
	at com.mesosphere.sdk.kubernetes.scheduler.tls.StateStoreTLSStore.loadServiceAccountKeyPair(StateStoreTLSStore.java:69)
	at com.mesosphere.sdk.kubernetes.scheduler.tls.OpenTLSProvisioner.initializeServiceAccountKeyPair(OpenTLSProvisioner.java:64)
	at com.mesosphere.sdk.kubernetes.scheduler.tls.TLSProvisioner.initialize(TLSProvisioner.java:63)
	at com.mesosphere.sdk.kubernetes.scheduler.Main.main(Main.java:61)
Caused by: com.mesosphere.sdk.state.StateStoreException: Key cannot contain '/' (reason: LOGIC_ERROR)
	at com.mesosphere.sdk.state.StateStore.validateKey(StateStore.java:582)
	at com.mesosphere.sdk.state.StateStore.fetchProperty(StateStore.java:387)
	at com.mesosphere.sdk.kubernetes.scheduler.tls.StateStoreTLSStore.loadServiceAccountKeyPair(StateStoreTLSStore.java:60)
	... 3 more
I0111 10:59:21.747092    11 executor.cpp:925] Command exited with status 1 (pid: 15)
I0111 10:59:22.748448    14 process.cpp:1072] Failed to accept socket: future discarded
```

@bmcstdio any idea what is triggering this?

**Comment by deric** [comment]
I wasn't using any certificate, I've just installed `beta-kubernetes` with default parameters on DC/OS 1.10.3 (open-source).

**Comment by pires** [comment]
ping @bmcstdio

**Comment by bmcstdio** [comment]
@deric are you able to reproduce this issue consistently? Can you please share some more details about your DC/OS cluster and how it was bootstrapped (Terraform, `dcos-launch`, custom)?

**Comment by deric** [comment]
@bmcstdio On premise installation via advanced installed (bootstrap server), if it makes any difference. The only change I've made was modifying application ID to `/dev/k8s`.

**Comment by pires** [comment]
@deric the problem is the application ID. We don't support namespaces (yet?), so please remove the slashes.

I'm re-assigning this to @spahl as he's our GrandMaster of DC/OS and roadmap.

**Comment by pires** [comment]
Next release will have a check that will fail earlier and complain about this. This limitation will also be documented in the installation section.
